### ISSUE TITLE
Pyinstaller makes this not working

### ISSUE THREAD

**Issue by AlexPaiva** [kaliiiiiiiiii/Selenium-Profiles#102]
**Describe the bug**
Using pyinstalelr to turn a script into an .exe makes the driver not open, simply flash a console and not open.

**To Reproduce**
```
from selenium_profiles.webdriver import Chrome
from selenium_profiles.profiles import profiles
from selenium_driverless.webdriver import ChromeOptions
from selenium_driverless.types.by import By

profile = profiles.Windows()  # or .Android
options = ChromeOptions()
# options.add_argument("--headless=new")
driver = Chrome(profile, options=options, driverless_options=True)

# get url
driver.get('https://nowsecure.nl#relax')  # test fingerprint

driver.quit()  # Execute on the End!
```

**Expected behavior or error-message**
```
No error messages
```

**Environment (please complete the following information):**
 - OS: Windows
- OS-Version 10
- Browser Chrome latest
 - Selenium-Profiles Version Latest
 - Selenium Version Latest
 - selenium-driverless Version Latest
 - Python versin 3.10

**Additional context**
Initially it gave a missing 'Failed to execute script 'pyi_rth_wind32api' due to unhandled exception: DLL load failed' error but manually adding it as a binary import seems to work.

**Comment by AlexPaiva** [comment]
Also getting:
```
2023-09-05 00:10:34 - FATAL ERROR OCCURED: Traceback (most recent call last):
  File "main.py", line 4495, in signup
  File "concurrent\futures\_base.py", line 446, in result
  File "concurrent\futures\_base.py", line 391, in __get_result
  File "concurrent\futures\thread.py", line 58, in run
  File "main.py", line 4199, in gamiCalli
  File "selenium_profiles\profiles\profiles.py", line 12, in Windows
  File "selenium_profiles\profiles\profiles.py", line 6, in return_profile
  File "selenium_profiles\utils\utils.py", line 33, in read_json
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Alex\\AppData\\Local\\Temp\\_MEI105282\\selenium_profiles/profiles/default.json'

```

**Comment by kaliiiiiiiiii** [comment]
@AlexPaiva 
1. Have you checked if the `--user-data-dir=C:/some_path/data` is valid?
2. The chrome process starts at https://github.com/kaliiiiiiiiii/Selenium-Driverless/blob/4e478d26ce7090192ff45d835e1efb31bd7bf98c/src/selenium_driverless/webdriver.py#L220 , check what path & arguments are there.

**Comment by kaliiiiiiiiii** [comment]
@AlexPaiva Does it work with `driverless_options=False` btw?
