### ISSUE TITLE
ERROR TRYING SELENIUM-PROFILE WITH PROXY ON WINDOWS RDP

### ISSUE THREAD

**Issue by alimayorru** [kaliiiiiiiiii/Selenium-Profiles#106]
I TRIED THE PROXY ON NORMAL CHROME BROWSER AND IT WORKED, ALSO TRIED THE CODE ON MY PHYSICAL WINDOWS AND IT WORKED TO, BUT TRYING SAME CODE ON AN RDP I GOT SOME ERRORS BELOW, DON'T KNOW IF YOU CAN INTERPRET IT.

NOTE I CAN'T PROVIDE CODE BECAUSE IT'S FOR A CLIENT  AND IT'S BUCKY.

THRACEBACK 

```Traceback (most recent call last):
  File "C:\Users\Usvps\PycharmProjects\pythonProject\main.py", line 556, in visit_url1
    driver = Chrome(profile, options=options, uc_driver=False)
  File "C:\Users\Usvps\PycharmProjects\pythonProject\venv\lib\site-packages\selenium_profiles\webdriver.py", line 180, in __init__
    self.profiles.proxy.set_single(proxy["proxy"], bypass_list=proxy["bypass_list"])
  File "C:\Users\Usvps\PycharmProjects\pythonProject\venv\lib\site-packages\selenium_profiles\scripts\proxy.py", line 63, in set_single
    self._injector.proxy.set_single(**proxy)
  File "C:\Users\Usvps\PycharmProjects\pythonProject\venv\lib\site-packages\selenium_injector\scripts\injector.py", line 241, in set_single
    if self.auth:
  File "C:\Users\Usvps\PycharmProjects\pythonProject\venv\lib\site-packages\selenium_injector\scripts\injector.py", line 221, in auth
    return self.socket.exec(self.socket.js.types.path("proxy.credentials"),
  File "C:\Users\Usvps\PycharmProjects\pythonProject\venv\lib\site-packages\selenium_injector\scripts\socket.py", line 27, in exec
User not connected
    result = self.post(json.dumps(script), user=user, timeout=timeout, start_time=start_time, interval=interval)
  File "C:\Users\Usvps\PycharmProjects\pythonProject\venv\lib\site-packages\selenium_injector\scripts\sync_websocket.py", line 109, in post
    self.send(message=parsed, user=user, timeout=timeout, start_time=start_time, interval=interval)
  File "C:\Users\Usvps\PycharmProjects\pythonProject\venv\lib\site-packages\selenium_injector\scripts\sync_websocket.py", line 96, in send
    user = self.wait_user(user, timeout=timeout, interval=interval, start_time=start_time)
  File "C:\Users\Usvps\PycharmProjects\pythonProject\venv\lib\site-packages\selenium_injector\scripts\sync_websocket.py", line 144, in wait_user
    raise TimeoutError("User not connected")
TimeoutError: User not connected
```

**Comment by kaliiiiiiiiii** [comment]
@alimayorru Well then I can't help you:)

**Comment by kaliiiiiiiiii** [comment]
@alimayorru Legacy speaking, you'd not even be allowed to use this package commercially (see License).
